### ISSUE TITLE
Resets project viewer position each startup

### ISSUE THREAD

**Issue by cysabi** [jccguimaraes/project-viewer-plus#45] opened 2019-06-03 01:47 UTC
Instead of having a config option that sets which side the project viewer is on, just make it a static dock that the user can place wherever they want, That way if the user places it in a unique position, Atom will take care of it itself.

**Comment by jccguimaraes** [comment] 2019-06-16 09:30
you can drag it to the left or right. Or do it via config.

**Comment by cysabi** [comment] 2019-06-18 04:48
Yes, however, any more complicated movement, such as creating a new panel under the tree view panel:
```
-----                                 |
Tree View Panel                       |
                                      |---.
--------------------------------------| > |
project-viewer-plus panel             |---`
                                      |
-----                                 |
```
*gotta love my ascii art skills :wink:*

This configuration will be reset each time you reload atom back to just 2 tabs at the top:
```
Tree View Panel  |  project-viewer-plus panel  |
                 |                             |---.
                 |-----------------------------| > |
                                               |---`
                                               |
```
*again with my top-notch ascii drawing skills*

This can be solved (hopefully easily) by just not having a config that sets the side the tab is on at all, since you can drag the tab anyway, simply allow the user to place the tab wherever

**Comment by jccguimaraes** [comment] 2019-06-18 07:55
they are so beautiful 😢!

Now I understand what you meant! I will have a look into the possibilities.

**Comment by jccguimaraes** [comment] 2019-06-18 07:57
Removing the option seems the better approach. I get the feeling it will be a mess otherwise and I have decided to not complicate things anymore or this package never sees the light of day

**Comment by jccguimaraes** [comment] 2019-08-03 13:55
This is proven to be a challenge xD
As there is no public API for this configuration.
Slow progress.

**Comment by jccguimaraes** [comment] 2019-08-09 00:16
@LeptoSpira managed to accomplish this. Running more tests since I have probably found in Atom itself.

**Comment by jccguimaraes** [comment] 2019-08-10 23:00
should be working now @LeptoSpira, although I would not advise you set it up on the left dock, it seems tree-view gets duplicated and basically crashes atom, need some hack on the inspector to remove the duplicate instance. Please tell me if this feature is implemented. thanks

**Comment by cysabi** [comment] 2019-08-11 02:32
I switched to Atom nightly, but after updating your package, it seems to stop working. The commands don't appear on the command palette, (so I cannot update the database file).

And the window is just empty...

**Comment by jccguimaraes** [comment] 2019-08-11 08:09
Strange, i just used the Atom Beta and it's working. Do you have `file-icons` installed or in anyway didn't click yes when pvp added the option?
Is there any errors in the dev tools windows?

**Comment by jccguimaraes** [comment] 2019-08-14 19:46
closing at this seems to work as intended

**Closed as completed by jccguimaraes** 2019-08-14 19:46 UTC
